# defaults for Kalman filter settings
DEFAULT_UNCERTAINTY_POS = 10
DEFAULT_UNCERTAINTY_VELO = 20
DEFAULT_PROCESS_UNCERTAINTY = 1e-9
DEFAULT_PROCESS_UNCERTAINTY_STEP = 1e-9
DEFAULT_STATE_UNCERTAINTY = DEFAULT_UNCERTAINTY_POS
